name: Publish to Exchange & Deploy to CH2.0

on:
  push:
    branches: [ main ]
    
jobs:         
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: 11
      
      - name: Publish to Exchange
        run: |
          mvn deploy --settings .maven/settings.xml -DskipMunitTests \
          -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}"

       name: Deploy to CloudHub 2.0 with Full Debug
  run: |
    mvn -X -e -Dmule.verboseLog=true \
    -Dorg.slf4j.simpleLogger.log.org.mule.tools.client=debug \
    -Dorg.slf4j.simpleLogger.log.org.apache.http=debug \
    -Dorg.slf4j.simpleLogger.log.org.apache.http.wire=debug \
    clean package mule:deploy --settings .maven/settings.xml -DskipMunitTests \
    -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
    -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}"
